version: '3.8'

services:
  urlpixel:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Optional API key - uncomment and set to enable authentication
      # - API_KEY=your-secret-api-key
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
